### PR TITLE
Stylint 1.0

### PR DESCRIPTION
**Pull request by danielhusar**
WIP

### CODE REVIEW

**Comment by danielhusar** [comment]
Hey @rossPatton any idea why the last test is still failing ? I think it should't be logging any warnings based on that custom configrc.

**Comment by rossPatton** [comment]
I'll try to take a look tonight ( or barring that, this weekend hopefully )

**Comment by danielhusar** [comment]
Cool thanks a lot.

**Comment by SimenB** [comment]
Any news? :smile: 

Was confused when the options in the readme of stylint did nothing until I discovered 0.9.x has some as `true`|`false` (semicolons in my case).

**Comment by rossPatton** [comment]
the options pertain to post 1.0.

1.0 changed a lot of the functionality. if it makes sense, i could also include the readme for pre-1.0 to clear up confusion.

sorry for my lack of responsiveness lately - i've been on vacation (and still am until monday) and just haven't been checking my computer much.

**Comment by SimenB** [comment]
Nah,  it's good now. I'd rather this plugin make a note about which version is included. 

Or even better, get this merged 😁

**Comment by danielhusar** [comment]
The issue here is, that my tests are failing when providing custom config so far.

**Comment by SimenB** [comment]
Default reporter prints "Stylint: You're all clear!" or something like that on no violations, doesn't it?

**Comment by rossPatton** [comment]
@SimenB yes

**Comment by danielhusar** [comment]
Thanks guys, I fixed the test and now this plugin uses latest version of stylint :)

**Comment by rossPatton** [comment]
Awesome! :+1:

**Pull request merged**
