### PR TITLE
Update options passed to stylus

### PR DESCRIPTION
**Pull request by gnayrr**
The reporter options being passed to stylus cannot be an object.

### CODE REVIEW

**Comment by gnayrr** [comment]
This was causing errors to be thrown when an object is passed to `gulp-stylus` for reporter.

```
assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: path must be a string
    at Module.require (module.js:366:3)
    at require (internal/module.js:20:19)
    at Object.init (/home/gnayrr/Perforce/lee_working/build2/node_modules/stylint/src/core/init.js:32:19)
    at /home/gnayrr/Perforce/lee_working/build2/node_modules/stampit/stampit.js:88:25
    at forEach (/home/gnayrr/Perforce/lee_working/build2/node_modules/mout/array/forEach.js:15:27)
    at Function.factory [as create] (/home/gnayrr/Perforce/lee_working/build2/node_modules/stampit/stampit.js:86:7)
...
```

**Comment by danielhusar** [comment]
Thanks!

Do you mind to add test that fail without this patch ?

**Comment by SimenB** [comment]
Merged as part of #27

**Comment by SimenB** [comment]
Will make a release after we can make it work with latest stylint, see #28

**Pull request closed without merging**
